# Generated by Django 3.0.7 on 2020-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMUtils', '0002_auto_20201219_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger_Broker',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateField(null=True)),
            ],
            options={
                'db_table': 'logger_broker',
            },
        ),
    ]
