# Generated by Django 3.0.7 on 2020-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMUtils', '0003_logger_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger_broker',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logger_outgoing_request',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logger_transaction',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
