# Generated by Django 3.0.7 on 2020-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=256)),
                ('api_secret', models.CharField(max_length=256)),
                ('account_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'broker_account',
            },
        ),
        migrations.CreateModel(
            name='CoinMarketCapModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('currency_id', models.IntegerField(default=0, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0, null=True)),
                ('price_usd', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('volume_usd_24h', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('percent_change_1h', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('market_cap', models.DecimalField(decimal_places=9, default=0, max_digits=39, null=True)),
                ('cmc_date_added', models.DateTimeField(db_index=True, null=True)),
                ('cmc_last_updated', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'coinmarketcap_coin_listing',
            },
        ),
        migrations.CreateModel(
            name='CoinMarketCapPairModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('market_pair', models.CharField(db_index=True, max_length=100)),
                ('base_currency', models.CharField(db_index=True, max_length=100)),
                ('market_currency', models.CharField(db_index=True, max_length=100)),
                ('market_currency_id', models.IntegerField(db_index=True, default=0, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'coinmarketcap_pair_listing',
                'unique_together': {('broker_id', 'market_pair')},
            },
        ),
        migrations.CreateModel(
            name='BrokerMarketPairModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('market_pair', models.CharField(db_index=True, max_length=100)),
                ('base_currency', models.CharField(db_index=True, max_length=100)),
                ('market_currency', models.CharField(db_index=True, max_length=100)),
                ('last_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('bid_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('ask_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'broker_market_pair',
                'unique_together': {('broker_id', 'market_pair')},
            },
        ),
        migrations.CreateModel(
            name='BrokerCoinPriceModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_name', models.CharField(default='', max_length=100)),
                ('coin_symbol', models.CharField(db_index=True, max_length=100)),
                ('coin_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('usd_last_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('usd_bid_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('usd_ask_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('btc_last_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('btc_bid_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('btc_ask_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'broker_coin_price',
                'unique_together': {('broker_id', 'coin_symbol')},
            },
        ),
        migrations.CreateModel(
            name='Broker_Account_Order_Fill',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('market_pair', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=100)),
                ('orderId', models.CharField(db_index=True, max_length=100)),
                ('trade_id', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('quantity', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'broker_account_order_fill',
                'unique_together': {('broker_id', 'trade_id')},
            },
        ),
        migrations.CreateModel(
            name='Broker_Account_Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('market_pair', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('orderId', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('quantity', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('fill_quantity', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('avg_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('status', models.CharField(default='NEW', max_length=100)),
            ],
            options={
                'db_table': 'broker_account_order',
                'unique_together': {('broker_id', 'orderId')},
            },
        ),
    ]
