# Generated by Django 3.0.7 on 2020-11-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='coin_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
