# Generated by Django 3.0.7 on 2020-11-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0002_auto_20201109_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='coin_name',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
