# Generated by Django 3.0.7 on 2020-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0003_auto_20201109_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_order',
            name='total_amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True),
        ),
    ]
