# Generated by Django 3.0.7 on 2020-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0004_broker_account_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmarketcapmodel',
            name='currency_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
