# Generated by Django 3.0.7 on 2021-01-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0009_brokercoinpricemodel_market_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokercoinpricemodel',
            old_name='market_pair',
            new_name='base_currency',
        ),
    ]
