# Generated by Django 3.0.7 on 2021-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0010_auto_20210109_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker_Account_Balance',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('free_balance', models.DecimalField(decimal_places=8, default=0, max_digits=29, null=True)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=29, null=True)),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'broker_account_balance',
                'unique_together': {('broker_id', 'coin_symbol')},
            },
        ),
    ]
