# Generated by Django 3.0.7 on 2021-01-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0011_broker_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_balance',
            name='updated_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
