# Generated by Django 3.0.7 on 2021-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0012_broker_account_balance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_balance',
            name='total_balance_in_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=29, null=True),
        ),
    ]
