# Generated by Django 3.0.7 on 2021-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0013_broker_account_balance_total_balance_in_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker_Account_Deposit_History',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('broker_history_id', models.IntegerField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=29, null=True)),
                ('confirmations', models.IntegerField(default='0', max_length=5)),
                ('txid', models.CharField(max_length=255)),
                ('crypto_address', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'broker_account_deposit_history',
                'unique_together': {('broker_id', 'broker_history_id')},
            },
        ),
    ]
