# Generated by Django 3.0.7 on 2021-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0014_broker_account_deposit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker_account_deposit_history',
            name='broker_history_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='broker_account_deposit_history',
            name='confirmations',
            field=models.IntegerField(default='0'),
        ),
    ]
