# Generated by Django 3.0.7 on 2021-01-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0015_auto_20210109_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_deposit_history',
            name='crypto_address_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
