# Generated by Django 3.0.7 on 2021-01-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0016_broker_account_deposit_history_crypto_address_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker_account_deposit_history',
            name='broker_history_id',
            field=models.CharField(max_length=255),
        ),
    ]
