# Generated by Django 3.0.7 on 2021-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0017_auto_20210109_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker_Account_Deposit_Address',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('crypto_address', models.CharField(max_length=255)),
                ('crypto_address_tag', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'broker_account_deposit_address',
                'unique_together': {('broker_id', 'coin_symbol')},
            },
        ),
    ]
