# Generated by Django 3.0.7 on 2021-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0018_broker_account_deposit_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker_Coin_Info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('withdraw_fee_type', models.CharField(max_length=255)),
                ('min_transact_fee_withdraw', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('max_transact_fee_withdraw', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'broker_coin_info',
                'unique_together': {('broker_id', 'coin_symbol')},
            },
        ),
    ]
