# Generated by Django 3.0.7 on 2021-01-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0020_auto_20210109_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_deposit_history',
            name='account_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
