# Generated by Django 3.0.7 on 2021-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0021_broker_account_deposit_history_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_deposit_address',
            name='chain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='broker_account_deposit_address',
            unique_together={('broker_id', 'coin_symbol', 'chain')},
        ),
    ]
