# Generated by Django 3.0.7 on 2021-01-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0022_auto_20210123_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker_Withdraw_History',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=255)),
                ('unique_id', models.CharField(default='', max_length=255)),
                ('txId', models.CharField(db_index=True, max_length=255)),
                ('network', models.CharField(db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'broker_account_withdraw_history',
                'unique_together': {('broker_id', 'unique_id')},
            },
        ),
    ]
