# Generated by Django 3.0.7 on 2021-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0023_broker_withdraw_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker_account_deposit_address',
            name='account_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='broker_account_deposit_address',
            unique_together={('broker_id', 'coin_symbol', 'chain', 'account_id')},
        ),
    ]
