# Generated by Django 3.0.7 on 2021-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0024_auto_20210126_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker_account_order',
            name='avg_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_account_order',
            name='fill_quantity',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_account_order',
            name='price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_account_order',
            name='quantity',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_account_order_fill',
            name='price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_account_order_fill',
            name='quantity',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_coin_info',
            name='max_transact_fee_withdraw',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_coin_info',
            name='min_transact_fee_withdraw',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_withdraw_history',
            name='amount',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='broker_withdraw_history',
            name='fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='btc_ask_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='btc_bid_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='btc_last_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='usd_ask_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='usd_bid_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokercoinpricemodel',
            name='usd_last_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokermarketpairmodel',
            name='ask_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokermarketpairmodel',
            name='bid_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='brokermarketpairmodel',
            name='last_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='coinmarketcapmodel',
            name='price_usd',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
    ]
