# Generated by Django 3.0.7 on 2021-05-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMBrokers', '0025_auto_20210219_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmarketcapmodel',
            old_name='rank',
            new_name='cmc_rank',
        ),
    ]
