# Generated by Django 3.0.7 on 2020-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerCoinPriceModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('coin_name', models.CharField(default='', max_length=100)),
                ('coin_symbol', models.CharField(max_length=100)),
                ('usd_bid_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('usd_ask_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('vnd_bid_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('vnd_ask_price', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('usd_rate_vnd', models.IntegerField(default=0, null=True)),
                ('client_buy_profit', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('client_sell_profit', models.DecimalField(decimal_places=9, default=1, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'exchanger_coin_price',
            },
        ),
        migrations.CreateModel(
            name='ExchangerCoinSetting',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('coin_name', models.CharField(default='', max_length=100)),
                ('coin_symbol', models.CharField(max_length=100, null=True)),
                ('client_buy_profit', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('client_sell_profit', models.DecimalField(decimal_places=9, default=1, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('coin_group', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'exchanger_coin_setting',
            },
        ),
        migrations.CreateModel(
            name='ExchangerTransaction',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('trade_mode', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('coin_id', models.CharField(max_length=100)),
                ('base_currency', models.CharField(max_length=100)),
                ('coin_amount', models.DecimalField(decimal_places=9, max_digits=19)),
                ('coin_amount_filled', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('reserved_amount', models.DecimalField(decimal_places=9, max_digits=19)),
                ('reserved_remainings', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('actual_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('estimate_vnd_amount', models.DecimalField(decimal_places=9, max_digits=29, null=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True)),
                ('fee_reserved', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('total_amount', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('total_amount_after_fee', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('wallet_payload', models.TextField()),
                ('wallet_status', models.IntegerField(default=0, null=True)),
                ('wallet_response', models.TextField()),
                ('wallet_request_count', models.IntegerField(default=0, null=True)),
                ('display_status', models.CharField(max_length=100)),
                ('system_status', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'exchanger_transaction',
            },
        ),
        migrations.CreateModel(
            name='ExchangerTransactionStep',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('trade_mode', models.CharField(max_length=100)),
                ('market_pair', models.CharField(max_length=100)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('broker_unique_id', models.CharField(max_length=100)),
                ('coin_amount', models.DecimalField(decimal_places=9, max_digits=19)),
                ('coin_amount_filled', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('actual_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('total_amount', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('total_amount_after_fee', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('wallet_payload', models.TextField()),
                ('wallet_status', models.IntegerField(default=0, null=True)),
                ('wallet_response', models.TextField()),
                ('wallet_request_count', models.IntegerField(default=0, null=True)),
                ('system_status', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'exchanger_transaction_step',
            },
        ),
    ]
