# Generated by Django 3.0.7 on 2020-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0002_auto_20201109_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerAdminSetting',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(max_length=100, unique=True)),
                ('setting_number_value', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('setting_text_value', models.CharField(default='Unknown', max_length=100)),
            ],
            options={
                'db_table': 'exchanger_admin_setting',
            },
        ),
    ]
