# Generated by Django 3.0.7 on 2020-11-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0003_exchangeradminsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeradminsetting',
            name='setting_number_value',
            field=models.DecimalField(decimal_places=9, default=1, max_digits=19),
        ),
    ]
