# Generated by Django 3.0.7 on 2020-11-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0004_auto_20201113_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='usd_rate_vnd',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
