# Generated by Django 3.0.7 on 2020-11-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0006_auto_20201113_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangertransactionstep',
            name='actual_usd_price',
        ),
    ]
