# Generated by Django 3.0.7 on 2020-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0007_remove_exchangertransactionstep_actual_usd_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='actual_price',
            new_name='avg_price_usd',
        ),
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='price',
            new_name='avg_price_vnd',
        ),
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='coin_amount',
            new_name='coin_amount_submitted',
        ),
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='total_amount',
            new_name='cost_amount',
        ),
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='total_amount_after_fee',
            new_name='cost_amount_after_fee',
        ),
        migrations.RenameField(
            model_name='exchangertransaction',
            old_name='total_fee',
            new_name='total_final_fee',
        ),
        migrations.RenameField(
            model_name='exchangertransactionstep',
            old_name='coin_amount',
            new_name='coin_amount_submitted',
        ),
        migrations.RenameField(
            model_name='exchangertransactionstep',
            old_name='total_amount',
            new_name='cost_amount',
        ),
        migrations.RenameField(
            model_name='exchangertransactionstep',
            old_name='total_amount_after_fee',
            new_name='cost_amount_after_fee',
        ),
        migrations.AddField(
            model_name='exchangertransaction',
            name='submitted_price_vnd',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='coin_amount_remainings',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='final_btc_price',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='market_total_amount_filled',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='market_total_amount_submitted',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstep',
            name='submitted_price',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
