# Generated by Django 3.0.7 on 2020-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0008_auto_20201115_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransaction',
            name='market_total_amount_filled',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransaction',
            name='market_total_amount_submitted',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
