# Generated by Django 3.0.7 on 2020-11-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0009_auto_20201115_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerTransactionStepLimit',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('trade_mode', models.CharField(max_length=100)),
                ('market_pair', models.CharField(max_length=100)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('broker_unique_id', models.CharField(max_length=100)),
                ('coin_amount_submitted', models.DecimalField(decimal_places=9, max_digits=19)),
                ('coin_amount_filled', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('coin_amount_remainings', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('submitted_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('vnd_match_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('usd_rate_vnd', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('final_btc_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('final_usd_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('cost_amount', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('cost_amount_after_fee', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('wallet_payload', models.TextField()),
                ('wallet_status', models.IntegerField(default=0, null=True)),
                ('wallet_response', models.TextField()),
                ('wallet_request_count', models.IntegerField(default=0, null=True)),
                ('system_status', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'exchanger_transaction_step_limit',
            },
        ),
        migrations.CreateModel(
            name='ExchangerTransactionStepMarket',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('trade_mode', models.CharField(max_length=100)),
                ('market_pair', models.CharField(max_length=100)),
                ('broker_id', models.CharField(db_index=True, max_length=100)),
                ('broker_unique_id', models.CharField(max_length=100)),
                ('market_total_amount_submitted', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('market_total_amount_filled', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('usd_rate_vnd', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('final_btc_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('final_usd_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('total_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('cost_amount', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('cost_amount_after_fee', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('wallet_payload', models.TextField()),
                ('wallet_status', models.IntegerField(default=0, null=True)),
                ('wallet_response', models.TextField()),
                ('wallet_request_count', models.IntegerField(default=0, null=True)),
                ('system_status', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'exchanger_transaction_step_market',
            },
        ),
        migrations.DeleteModel(
            name='ExchangerTransactionStep',
        ),
    ]
