# Generated by Django 3.0.7 on 2020-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0010_auto_20201115_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='coin_amount_filled',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
