# Generated by Django 3.0.7 on 2020-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0011_exchangertransactionstepmarket_coin_amount_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransaction',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exchangertransaction',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
