# Generated by Django 3.0.7 on 2020-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0017_exchangertransactionsteplimit_final_money_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransaction',
            name='fee_refund',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True),
        ),
    ]
