# Generated by Django 3.0.7 on 2020-11-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0018_exchangertransaction_fee_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='client_buy_profit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinsetting',
            name='client_buy_profit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True),
        ),
    ]
