# Generated by Django 3.0.7 on 2020-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0020_auto_20201122_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionsteplimit',
            name='coin_fee',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True),
        ),
    ]
