# Generated by Django 3.0.7 on 2020-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0022_auto_20201127_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='temp_cost_amount',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='temp_fee_amount',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
