# Generated by Django 3.0.7 on 2020-11-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0024_exchangertransactionstepmarket_temp_cost_amount_after_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='coin_fee',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='final_vnd_price',
            field=models.DecimalField(decimal_places=9, max_digits=19, null=True),
        ),
    ]
