# Generated by Django 3.0.7 on 2020-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0025_auto_20201128_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='final_money_added',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True),
        ),
    ]
