# Generated by Django 3.0.7 on 2020-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0026_exchangertransactionstepmarket_final_money_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerTransactionStepTrading',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('coin_id', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=100)),
                ('buy_id', models.IntegerField(db_index=True, default=0)),
                ('sell_id', models.IntegerField(db_index=True, default=0)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('leading_action', models.CharField(max_length=100)),
                ('coin_amount', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('final_vnd_price', models.DecimalField(decimal_places=9, max_digits=19, null=True)),
                ('buy_fee_percent', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('buy_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('sell_fee_percent', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('sell_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('exchanger_total_fee', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('cost_amount', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('cost_amount_after_fee_buy', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('cost_amount_after_fee_sell', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('final_money_added_buy', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('final_money_added_sell', models.DecimalField(decimal_places=9, default=0, max_digits=19, null=True)),
                ('wallet_payload', models.TextField()),
                ('wallet_status', models.IntegerField(default=0, null=True)),
                ('wallet_response', models.TextField()),
                ('wallet_request_count', models.IntegerField(default=0, null=True)),
                ('system_status', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'exchanger_transaction_step_trading',
            },
        ),
    ]
