# Generated by Django 3.0.7 on 2020-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0027_exchangertransactionsteptrading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangertransactionsteptrading',
            old_name='wallet_request_count',
            new_name='wallet_buy_request_count',
        ),
        migrations.RenameField(
            model_name='exchangertransactionsteptrading',
            old_name='wallet_status',
            new_name='wallet_buy_status',
        ),
        migrations.RemoveField(
            model_name='exchangertransactionsteptrading',
            name='wallet_payload',
        ),
        migrations.RemoveField(
            model_name='exchangertransactionsteptrading',
            name='wallet_response',
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_buy_payload',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_buy_response',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_sell_payload',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_sell_request_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_sell_response',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='wallet_sell_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
