# Generated by Django 3.0.7 on 2020-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0028_auto_20201129_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='buy_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='sell_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
