# Generated by Django 3.0.7 on 2020-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0029_auto_20201129_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='coin_id',
            field=models.CharField(max_length=100),
        ),
    ]
