# Generated by Django 3.0.7 on 2020-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0030_auto_20201129_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangertransactionsteptrading',
            name='action',
        ),
    ]
