# Generated by Django 3.0.7 on 2020-12-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0031_remove_exchangertransactionsteptrading_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangercoinsetting',
            name='is_allow_limit_trade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exchangercoinsetting',
            name='is_allow_market_trade',
            field=models.IntegerField(default=0),
        ),
    ]
