# Generated by Django 3.0.7 on 2021-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0032_auto_20201227_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangertransactionsteplimit',
            name='fulfillment_broker_unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exchangertransactionsteptrading',
            name='fulfillment_broker_unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
