# Generated by Django 3.0.7 on 2021-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0033_auto_20210103_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangertransactionsteptrading',
            name='fulfillment_broker_unique_id',
        ),
        migrations.AddField(
            model_name='exchangertransactionstepmarket',
            name='fulfillment_broker_unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
