# Generated by Django 3.0.7 on 2021-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0034_auto_20210103_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerWithdrawRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('coin_id', models.CharField(max_length=100)),
                ('to_coin_address', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=9, default=0, max_digits=29, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('broker_reference_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'exchanger_withdraw_request',
            },
        ),
    ]
