# Generated by Django 3.0.7 on 2021-01-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0035_exchangerwithdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerwithdrawrequest',
            name='txid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
