# Generated by Django 3.0.7 on 2021-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0036_exchangerwithdrawrequest_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerwithdrawrequest',
            name='wallet_request_count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='exchangerwithdrawrequest',
            name='wallet_status',
            field=models.IntegerField(default='0'),
        ),
    ]
