# Generated by Django 3.0.7 on 2021-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0037_auto_20210124_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangerCoinGroupSetting',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='Unknown', max_length=100)),
                ('client_buy_profit', models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True)),
                ('client_sell_profit', models.DecimalField(decimal_places=9, default=1, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True, null=True)),
                ('is_allow_market_trade', models.IntegerField(default=0)),
                ('is_allow_limit_trade', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'exchanger_coin_groups',
            },
        ),
    ]
