# Generated by Django 3.0.7 on 2021-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0038_exchangercoingroupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangercoingroupsetting',
            name='broker_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
