# Generated by Django 3.0.7 on 2021-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0040_exchangercoingroupsetting_coin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeradminsetting',
            name='setting_number_value',
            field=models.DecimalField(decimal_places=19, default=1, max_digits=29),
        ),
        migrations.AlterField(
            model_name='exchangercoingroupsetting',
            name='client_sell_profit',
            field=models.DecimalField(decimal_places=19, default=1, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='client_sell_profit',
            field=models.DecimalField(decimal_places=19, default=1, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='usd_ask_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='usd_bid_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='vnd_ask_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinpricemodel',
            name='vnd_bid_price',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangercoinsetting',
            name='client_sell_profit',
            field=models.DecimalField(decimal_places=19, default=1, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='avg_price_usd',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='avg_price_vnd',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='coin_amount_filled',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='coin_amount_submitted',
            field=models.DecimalField(decimal_places=19, max_digits=29),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='fee_refund',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='fee_reserved',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='market_total_amount_filled',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='market_total_amount_submitted',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='price_vnd_when_submit',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=19, max_digits=29),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='reserved_remainings',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='submitted_price_vnd',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransaction',
            name='total_final_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='coin_amount_filled',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='coin_amount_remainings',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='coin_amount_submitted',
            field=models.DecimalField(decimal_places=19, max_digits=29),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='coin_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='final_btc_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='final_usd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='final_vnd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='submitted_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='temp_vnd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='total_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='usd_rate_vnd',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteplimit',
            name='vnd_match_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='coin_amount_filled',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='coin_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='final_btc_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='final_usd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='final_vnd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='market_total_amount_filled',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='market_total_amount_submitted',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='temp_cost_amount',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='temp_cost_amount_after_fee',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='temp_fee_amount',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='total_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionstepmarket',
            name='usd_rate_vnd',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='buy_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='buy_fee_percent',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='coin_amount',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='cost_amount',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='cost_amount_after_fee_buy',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='cost_amount_after_fee_sell',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='exchanger_total_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='final_money_added_buy',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='final_money_added_sell',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='final_vnd_price',
            field=models.DecimalField(decimal_places=19, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='sell_fee',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='exchangertransactionsteptrading',
            name='sell_fee_percent',
            field=models.DecimalField(decimal_places=19, default=0, max_digits=29, null=True),
        ),
    ]
