# Generated by Django 3.0.7 on 2021-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0041_auto_20210219_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangercoinsetting',
            name='default_withdraw_network',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
