# Generated by Django 3.0.7 on 2021-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMExchanger', '0042_exchangercoinsetting_default_withdraw_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerwithdrawrequest',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
